// Reda design tokens — translated from the brand doc.
window.REDA_THEME = {
  colors: {
    red: '#E63027',
    redDim: '#C42821',
    black: '#0A0A0A',
    white: '#FFFFFF',
    surface: '#F5F5F5',
    surfaceAlt: '#FAFAFA',
    border: '#E5E5E5',
    borderStrong: '#D4D4D4',
    textPrimary: '#0A0A0A',
    textSecondary: '#7A7A7A',
    textTertiary: '#A3A3A3',
    success: '#16A34A',
    successSoft: '#DCFCE7',
    warning: '#F59E0B',
    warningSoft: '#FEF3C7',
    closed: '#7A7A7A',
    closedSoft: '#F0F0F0',
    redSoft: '#FEE2E0',
    info: '#2563EB',
  },
  // Status color map (filled variant uses bg + white text)
  status: {
    pending:        { label: 'Pending',        tone: 'red',    desc: 'Awaiting agent' },
    available:      { label: 'Available',      tone: 'red',    desc: 'Customer reachable' },
    not_answering:  { label: 'Not answering',  tone: 'amber',  desc: 'No answer' },
    number_busy:    { label: 'Number busy',    tone: 'amber',  desc: 'Line busy' },
    switched_off:   { label: 'Switched off',   tone: 'amber',  desc: 'Phone off' },
    tomorrow:       { label: 'Tomorrow',       tone: 'amber',  desc: 'Customer rescheduled' },
    postponed:      { label: 'Postponed',      tone: 'amber',  desc: 'Pushed later' },
    follow_up:      { label: 'Follow up',      tone: 'amber',  desc: 'Needs follow-up' },
    delivered:      { label: 'Delivered',      tone: 'green',  desc: 'Done' },
    cancelled:      { label: 'Cancelled',      tone: 'gray',   desc: 'Closed' },
    failed:         { label: 'Failed',         tone: 'gray',   desc: 'Could not deliver' },
    unserious:      { label: 'Unserious',      tone: 'gray',   desc: 'Customer not serious' },
    no_product:     { label: 'No product',     tone: 'gray',   desc: 'Out of stock' },
    rolled_over:    { label: 'Rolled over',    tone: 'gray',   desc: 'Carried to next day' },
  },
  font: '"Montserrat", system-ui, sans-serif',
  fontMono: '"JetBrains Mono", ui-monospace, monospace',
};
