// Valid bank names for the Moniepoint bulk-transfer upload, extracted verbatim
// from Moniepoint's official "Bulk-transfer-template.xlsx" Guide sheet
// (141 banks). The CSV's "Bank" column must contain one of these names
// (or an alias) or Moniepoint rejects the row, so the client bank-details form
// picks from this list rather than free-typing. `name` is the canonical value we
// store + emit in the CSV; `aliases` only widen the dropdown's search matching.
export type MoniepointBank = { name: string; aliases: string[] };

export const MONIEPOINT_BANKS: MoniepointBank[] = [
  { name: 'Access Bank Nigeria', aliases: ['ABP', 'Access Bank'] },
  { name: '9 PAYMENT SERVICE BANK', aliases: ['9PSB', '9 PAYMENT'] },
  { name: 'AB MICROFINANCE BANK', aliases: ['AB MFB', 'AB MICROFINANCE'] },
  { name: 'Abbey Mortgage Bank', aliases: ['ABBEY', 'Abbey Mortgage'] },
  { name: 'ACCION MICROFINANCE BANK', aliases: ['ACCION', 'ACCION MICROFINANCE'] },
  { name: 'AFEMAI MICROFINANCE BANK', aliases: ['AFEMAI MFB', 'AFEMAI MICROFINANCE'] },
  { name: 'AG MORTGAGE BANK', aliases: ['AGMB', 'AG MORTGAGE'] },
  { name: 'AKU Microfinance Bank', aliases: ['AKUMFB', 'AKU Microfinance'] },
  { name: 'AKWA SAVINGS & LOANS', aliases: ['AKWASAVINGS', 'AKWA SAVINGS'] },
  { name: 'Allianze MIcrofinace Bank', aliases: ['Allianze MFB', 'Allianze Microfinance'] },
  { name: 'ALTERNATIVE BANK LIMITED', aliases: ['ALT', 'ALTERNATIVE BANK'] },
  { name: 'Amoye Microfinance Bank', aliases: ['Amoye MFB', 'Amoye Microfinance'] },
  { name: 'Amucha Microfinance Bank', aliases: ['AMUCHAMFB', 'Amucha Microfinance'] },
  { name: 'Aniocha Microfinance Bank', aliases: ['Aniocha MFB', 'Aniocha Microfinance'] },
  { name: 'Aspire Microfinance Bank', aliases: ['ASPIREMFB', 'Aspire Microfinance'] },
  { name: 'Aztec Microfinance Bank Limited', aliases: ['Aztec MFB', 'Aztec Microfinance'] },
  { name: 'Baines Credit  Microfinance Bank', aliases: ['BAINESCREDITMFB', 'Baines Credit'] },
  { name: 'Banc Corp Microfinance Bank', aliases: ['BANCCORP', 'Banc Corp MFB'] },
  { name: 'BANKLY MICROFINANCE BANK', aliases: ['BANKLY MFB', 'BANKLY MICROFINANCE'] },
  { name: 'Baobab Microfinance Bank', aliases: ['BAOBABMFB', 'Baobab MFB'] },
  { name: 'Beststar Microfinance Bank', aliases: ['BESTSTARMFB', 'Beststar MFB'] },
  { name: 'Branch International Financial Services', aliases: ['Branch International', 'Branch'] },
  { name: 'BRIGHTWAY MICROFINANCE BANK', aliases: ['BRIGHTWAYMFB', 'BRIGHTWAY MFB'] },
  { name: 'Bunkure Microfinance Bank', aliases: ['Bunkure MFB', 'Bunkure Microfinance'] },
  { name: 'CAPSTONE MICROFINANCE BANK', aliases: ['CAPSTONE MFB', 'CAPSTONE MICROFINANCE'] },
  { name: 'CARBON', aliases: ['carbon', 'CARBON'] },
  { name: 'CASHRITE MICROFINANCE BANK', aliases: ['CASHRITE MFB', 'CASHRITE MICROFINANCE'] },
  { name: 'Chukwunenye Microfinance Bank', aliases: ['CHUKWUNENYEMFB', 'Chukwunenye MFB'] },
  { name: 'Citibank Nigeria', aliases: ['CITI', 'Citibank'] },
  { name: 'CORESTEP MICROFINANCE BANK', aliases: ['CORESTEP MFB', 'CORESTEP MICROFINANCE'] },
  { name: 'Coronation Merchant Bank', aliases: ['Coronation', 'Coronation Merchant'] },
  {
    name: 'CROSS RIVER MICROFINANCE BANK LTD',
    aliases: ['CROSS RIVER MFB', 'CROSS RIVER MICROFINANCE'],
  },
  { name: 'Delta Trust Mortgage Bank', aliases: ['DELTATRUSTMFB', 'Delta Trust Mortgage'] },
  { name: 'Diamond Bank', aliases: ['DBP', 'Diamond'] },
  { name: 'Dot Microfinance Bank', aliases: ['DOTMFB', 'Dot Microfinance'] },
  { name: 'Ecobank Nigeria', aliases: ['ECO', 'Ecobank'] },
  { name: 'Enterprise Bank', aliases: ['EPB', 'Enterprise'] },
  { name: 'eTranzact PocketMoni', aliases: ['ETZ', 'eTranzact'] },
  { name: 'EYOWO', aliases: ['EYOWO', 'EYOWO'] },
  { name: 'FairMoney', aliases: ['FAIRMONEY', 'FairMoney MFB'] },
  { name: 'FEDETH Microfinance Bank', aliases: ['FEDETHMFB', 'FEDETH Microfinance'] },
  { name: 'FFS MICROFINANCE BANK', aliases: ['FFS', 'FFS MFB'] },
  { name: 'Fidelity Bank', aliases: ['FBP', 'Fidelity'] },
  { name: 'FIDFUND MICROFINANCE BANK LIMITED', aliases: ['FIDFUND MFB', 'FIDFUND MICROFINANCE'] },
  { name: 'FINCA Nigeria', aliases: ['FINCA', 'FINCA'] },
  { name: 'Firmus Microfiance Bank', aliases: ['Firmus MFB', 'Firmus Microfiance'] },
  { name: 'First Bank of Nigeria', aliases: ['FBN', 'First Bank'] },
  { name: 'First City Monument Bank', aliases: ['FCMB', 'First City'] },
  { name: 'FirstMonie', aliases: ['FIRSTMONIE', 'FirstMonie'] },
  {
    name: 'FIRSTTUST MORTGAGE BANK NIG PLC',
    aliases: ['FIRSTTUST MORTGAGE', 'FIRSTTUST MORTGAGE BANK'],
  },
  { name: 'FLOURISH MICROFINANCE BANK', aliases: ['FLOURISH MFB', 'FLOURISH MICROFINANCE'] },
  { name: 'FSDH', aliases: ['FSDH', 'FSDH'] },
  { name: 'GLOBUS BANK', aliases: ['GLOBUS', 'GLOBUS BANK'] },
  { name: 'GoMoney', aliases: ['GoMoney', 'GoMoney'] },
  { name: 'Good News Microfinance Bank', aliases: ['GOODNEWSMFB', 'Good News MFB'] },
  { name: 'Guaranty Trust Bank', aliases: ['GTB', 'Guaranty Trust'] },
  { name: 'Haggai Mortgage Bank', aliases: ['Haggai', 'Haggai Mortgage'] },
  { name: 'Heritage Bank', aliases: ['HBP', 'Heritage'] },
  { name: 'HOPE PSB', aliases: ['HOPE', 'HOPE PAYMENT SERVICE BANK'] },
  {
    name: 'Ibom Fadama Microfinance Bank',
    aliases: ['Ibom Fadama MFB', 'Ibom Fadama Microfinance'],
  },
  { name: 'Infinity Microfinance Bank', aliases: ['InfinityMFB', 'Infinity Microfinance'] },
  { name: 'Infinity Trust Mortgage Bank', aliases: ['InfintyTrust', 'Infinity Trust Mortgage'] },
  { name: 'Iyamoye Microfinance Bank', aliases: ['IYAMOYEMFB', 'Iyamoye Microfinance'] },
  { name: 'Iyin Ekiti Microfinance Bank', aliases: ['Iyin Ekiti MFB', 'Iyin Ekiti Microfinance'] },
  { name: 'Jaiz Bank', aliases: ['JAIZ', 'Jaiz Bank'] },
  { name: 'Jubilee Life Mortgage Bank', aliases: ['JUBILEE', 'Jubilee Life Mortgage'] },
  { name: 'KANO POLY MICROFINANCE BANK', aliases: ['KANOPOLY MFB', 'KANO POLY MICROFINANCE'] },
  { name: 'KAYVEE Microfinance Bank', aliases: ['KAYMFB', 'KAYVEE MFB'] },
  { name: 'Keystone Bank', aliases: ['KSB', 'Keystone'] },
  { name: 'KOLOMONI MICROFINANCE BANK', aliases: ['KOLOMONI MFB', 'KOLOMONI MICROFINANCE'] },
  { name: 'Kredi Money Microfinance Bank', aliases: ['KREDIMONEYMFB', 'Kredi Money Microfinance'] },
  { name: 'Kuda Bank', aliases: ['KUDA', 'Kuda Bank'] },
  { name: 'LAPO MICROFINANCE BANK', aliases: ['LAPO', 'LAPO MFB'] },
  { name: 'Lotus bank', aliases: ['LOTUS', 'Lotus bank'] },
  {
    name: 'MAB ALLIANZ MICROFINANCE BANK',
    aliases: ['MAB ALLIANZ MFB', 'MAB ALLIANZ MICROFINANCE'],
  },
  { name: 'Mainland Microfinance Bank', aliases: ['Mainland MFB', 'Mainland Microfinance'] },
  { name: 'MainStreet Bank', aliases: ['MSB', 'MainStreet'] },
  { name: 'Manny Microfinance Bank', aliases: ['Manny', 'Manny MFB'] },
  {
    name: 'MICHAEL OKPARA UNIAGRIC MICROFINANCE BANK',
    aliases: ['MOU MFB', 'MICHAEL OKPARA UNIAGRIC MICROFINANCE'],
  },
  { name: 'MICROBIZ MICROFINANCE BANK', aliases: ['MICROBIZ MFB', 'MICROBIZ MICROFINANCE'] },
  { name: 'Mkobo Microfinance Bank', aliases: ['Mkobo MFB', 'Mkobo Microfinance'] },
  { name: 'MOMO PSB', aliases: ['MOMOPSB', 'MOMO PAYMENT SERVICE BANK'] },
  { name: 'Moneymaster PSB', aliases: ['MONEYMASTER', 'Moneymaster PAYMENT SERVICE BANK'] },
  { name: 'Moniepoint Microfinance Bank', aliases: ['Moniepoint MFB', 'Moniepoint'] },
  { name: 'NEPTUNE MICROFINANCE BANK', aliases: ['NEPTUNEMFB', 'NEPTUNE MICROFINANCE'] },
  { name: 'Nice Microfinance Bank LTD', aliases: ['NICE MFB', 'Nice Microfinance'] },
  {
    name: 'NIRSAL NATIONAL MICROFINANCE BANK',
    aliases: ['NIRSAL', 'NIRSAL NATIONAL MICROFINANCE'],
  },
  { name: 'Nomba', aliases: ['NOMBA', 'Nomba'] },
  { name: 'NowNow', aliases: ['NowNow', 'NowNow'] },
  { name: 'NPF MFB', aliases: ['NPF MFB', 'NPF Microfinance Bank'] },
  { name: 'Oche Microfinance Bank Ltd', aliases: ['Oche MFB', 'Oche Microfinance'] },
  { name: 'OPay', aliases: ['OPAY', 'OPay'] },
  { name: 'Otech Microfinance Bank Ltd', aliases: ['OtechMFB', 'Otech Microfinance'] },
  { name: 'PAGA', aliases: ['PAGA', 'PAGA'] },
  { name: 'PalmPay', aliases: ['PALMPAY', 'PalmPay'] },
  { name: 'Parallex Bank', aliases: ['PMFB', 'Parallex'] },
  { name: 'Parkway Microfinance Bank', aliases: ['PARKWAYMFB', 'Parkway Microfinance'] },
  { name: 'PAYSTACK PAYMENTS LIMITED', aliases: ['PAYSTACK', 'PAYSTACK PAYMENTS'] },
  { name: 'Peace Microfinance Bank', aliases: ['Peace Mfb', 'Peace Microfinance'] },
  { name: 'Pillar Microfinance Bank', aliases: ['PILLAR', 'Pillar Microfinance'] },
  { name: 'Polaris Bank', aliases: ['SKYE', 'Polaris'] },
  { name: 'PREEMINENT MFB', aliases: ['PREEMINENT MFB', 'PREEMINENT Microfinance Bank'] },
  { name: 'PremiumTrust Bank', aliases: ['PREMIUMTRUST', 'PremiumTrust'] },
  { name: 'PRISTINE DIVITIS MICROFINANCE BANK LTD', aliases: ['PRISTINE', 'PRISTINE DIVITIS MFB'] },
  { name: 'Providus Bank', aliases: ['PVB', 'Providus'] },
  { name: 'PYRAMID MICROFINANCE BANK', aliases: ['PYRAMID', 'PYRAMID MFB'] },
  { name: 'Rand Merchant Bank', aliases: ['RMB', 'Rand Merchant'] },
  { name: 'Regent MFB', aliases: ['REGENTMFB', 'Regent Microfinance Bank'] },
  { name: 'Rehoboth MFB', aliases: ['REHOBOTHMFB', 'Rehoboth Microfinance Bank'] },
  { name: 'Rigo Microfinance Bank', aliases: ['Rigo', 'Rigo MFB'] },
  { name: 'Rigo Microfinance Bank Limited', aliases: ['RIGOMFB', 'Rigo Microfinance'] },
  { name: 'Rubies MFB', aliases: ['Rubies', 'Rubies Microfinance Bank'] },
  { name: 'Safe Haven Microfinance Bank', aliases: ['Safe Haven MFB', 'Safe Haven Microfinance'] },
  { name: 'Signature Bank', aliases: ['SIGNATURE', 'Signature Bank'] },
  { name: 'SMARTCASH', aliases: ['SMARTCASH', 'SMARTCASH'] },
  { name: 'SPECTRUM MICROFINANCE BANK', aliases: ['SPECTRUM MFB', 'SPECTRUM MICROFINANCE'] },
  { name: 'Stanbic IBTC Bank', aliases: ['STANBIC', 'Stanbic IBTC'] },
  { name: 'Standard Chartered Bank', aliases: ['SCB', 'Standard Chartered'] },
  { name: 'Sterling Bank', aliases: ['SBP', 'Sterling'] },
  { name: 'Suntrust Bank', aliases: ['SUN', 'Suntrust'] },
  { name: 'SUPPORT MICROFINANCE BANK', aliases: ['SUPPORT MFB', 'SUPPORT MICROFINANCE'] },
  { name: 'TAJ Bank', aliases: ['TAJ', 'TAJ Bank'] },
  { name: 'Taj_Pinspay', aliases: ['TajPinspay', 'Taj_Pinspay'] },
  { name: 'TANADI MFB (CRUST)', aliases: ['TANADI', 'TANADI MFB'] },
  { name: 'Titan Trust Bank', aliases: ['Titan', 'Titan Trust'] },
  {
    name: 'Titan-Paystack Microfinance Bank',
    aliases: ['TITANPAYSTACKMFB', 'Titan-Paystack Microfinance'],
  },
  { name: 'Total Trust Microfinance Bank', aliases: ['Trust MFB', 'Total Trust Microfinance'] },
  { name: 'Uhuru Microfinance Bank', aliases: ['UHURU', 'Uhuru Microfinance'] },
  { name: 'UNICAL MICROFINANCE BANK', aliases: ['UNICALMFB', 'UNICAL MICROFINANCE'] },
  { name: 'Union Bank', aliases: ['UBN', 'Union'] },
  { name: 'United Bank For Africa', aliases: ['UBA', 'United Bank'] },
  { name: 'Unity Bank', aliases: ['UNITY', 'Unity Bank'] },
  { name: 'UNN Staff Microfinance Bank Ltd', aliases: ['UNN Staff MFB', 'UNN Staff Microfinance'] },
  { name: 'VALE FINANCE LIMITED', aliases: ['VFL', 'VALE FINANCE'] },
  { name: 'VFD microfinance bank', aliases: ['VFD', 'VFD MFB'] },
  { name: 'WAYA MICROFINANCE BANK', aliases: ['WAYA MFB', 'WAYA MICROFINANCE'] },
  { name: 'Wema Bank', aliases: ['WEMA', 'Wema Bank'] },
  { name: 'Yes Microfinance Bank', aliases: ['YESMFB', 'Yes Microfinance'] },
  { name: 'Zenith Bank', aliases: ['ZIB', 'Zenith'] },
  { name: 'ZENITH EAZY WALLET', aliases: ['ZE WALLET', 'ZENITH EAZY'] },
  { name: 'Zikora Microfinance Bank', aliases: ['ZIKORA', 'Zikora Microfinance'] },
];
